baseurl = "http://oguzhane.github.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-us"
layoutdir = "layouts"
publishdir = "public"
author = "Oguzhan Ergin"
title = "Oguzhan Ergin"
pygmentsuseclasses = true
theme = "cocoa"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Oguzhan Ergin"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Oguzhan Ergin - Blog"
email = "oguzhanergin13@gmail.com"
github = "//github.com/OguzhanE"
highlight = true